name: C++ Docker CI/CD Pipeline

# 1. Trigger: Define que es lo que inicializa este flujo
on:
  push:
    branches: [ main ] # Solamente ejecuta cuando meto algo en el main

# 2. Job: Define que tareas va estar ejecutando.
jobs:
  build_and_push_image:
    runs_on: ubuntu-latest
    steps:
      # Paso 1: Sacar el codigo
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      # Paso 2: Logear al sistema de Contenedores.
      - name: Log in to Docker Hub
        uses: docker/login -action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      # Paso 3: Crear la imagen del Docker
      - name: Build and Push C++ Docker Image DORO
        uses: docker/build-push-action@v5
        with:
          context: . # busca el Dockerfile en el directorio actual.
          push: true # Empuja la image resultado al registro
          tags: ${{secrets.DOCKER_USERNAME }}/mensaje-pila:latest

      # Paso 4: (opcional) Agregar una confirmacion de la etapa CD haya sido completado.
      - name: Deployment Confirmation
        run: | 
          echo "Successfully built and pushed the image to Docker Hub!"
          echo "Image: ${{secrets.DOCKER_USERNAME }}/mensaje-pila:latest"
